In [ ]:
import pandas as pd

production=pd.Series(
    [30,60,40,25],
    index=['Wheat','Rice','Maize','Barley']
    )

print(production)

Wheat     30
Rice      60
Maize     40
Barley    25
dtype: int64

In [ ]:

#By crop name(label)
print(production['Rice'])    # or print(production[1])
print(production.loc["Rice"]) # or print(production.iloc[1])

60
60

In [ ]:
import pandas as pd

production=pd.Series([30,60,40,25])

print(production)

0    30
1    60
2    40
3    25
dtype: int64

In [ ]:
print(production[1])
print(production.iloc[1])

60
60

/tmp/ipython-input-795029921.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(production[1])

In [ ]:
print(production.iloc[1])  # to avoid the warning

60

In [ ]:
print(production.sum())
print(production.mean())
print(production.max())   #prints the index holding max value
print(production.idxmax()) # Maximum production crop
#it prints the index label of the max value in the Series
print(production.idxmax(),"is having max value of",production.max())

155
38.75
60
Rice
Rice is having max value of 60

In [ ]:
#increase all production by 10%
inc_production=production*1.10
print(inc_production)

Wheat     33.0
Rice      66.0
Maize     44.0
Barley    27.5
dtype: float64

In [ ]:
 #crops with production >40 tons
high_production=production[production>40]
print(high_production)
print()

print(production>40)

Rice    60
dtype: int64

Wheat     False
Rice       True
Maize     False
Barley    False
dtype: bool

In [ ]:
import pandas as pd
df=pd.DataFrame({
    "Name":["Akhil","Lalitha","Radha"],
    "Age" :[25,35,30],
    "City" :["NY","WN","LA"]
},index=['a','b','c'])

print(df)
print("\n",df.loc['b'])

      Name  Age City
a    Akhil   25   NY
b  Lalitha   35   WN
c    Radha   30   LA

 Name    Lalitha
Age          35
City         WN
Name: b, dtype: object

In [ ]:
import pandas as pd
data= {"Name":["Akhil","Lalitha","Radha"],
      "Age" :[25,35,30],
      "City" :["NY","WN","LA"]}
df=pd.DataFrame(data,index=['a','b','c']) #we can store the dictionary into a variable also

print(df)
print("\n",df.loc['b'])

      Name  Age City
a    Akhil   25   NY
b  Lalitha   35   WN
c    Radha   30   LA

 Name    Lalitha
Age          35
City         WN
Name: b, dtype: object

In [ ]:
print(df)
print()
print(df.loc[['a','c'],['Name','City']])

      Name  Age City
a    Akhil   25   NY
b  Lalitha   35   WN
c    Radha   30   LA

    Name City
a  Akhil   NY
c  Radha   LA

In [ ]:
print(df.loc['a':'c'])
print("\n",df.iloc[0:2])

      Name  Age City
a    Akhil   25   NY
b  Lalitha   35   WN
c    Radha   30   LA

       Name  Age City
a    Akhil   25   NY
b  Lalitha   35   WN

In [ ]:
#conditional statement  #11th Feb
import pandas as pd
data= {"Name":["Akhil","Lalitha","Radha"],
      "Age" :[25,35,30],
      "City" :["NY","WN","LA"]}
df=pd.DataFrame(data,index=['a','b','c'])

print(df.loc[df["Age"]>28,['Name','Age']])

      Name  Age
b  Lalitha   35
c    Radha   30

In [ ]:
print(df.iloc[[0,2]])

    Name  Age City
a  Akhil   25   NY
c  Radha   30   LA

In [ ]:
print(df.iloc[[0,2],[1,2]]) #select rows and column by position

   Age City
a   25   NY
c   30   LA

In [ ]:
import pandas as pd

data={
    'Farm': ['Farm A','Farm B','Farm C','Farm D'],
    'Crop': ['Wheat','Rice','Wheat','Sorghum'],
    'Area_ha': [10,15,20,36],
    'Production_tons': [30,40,50,60]
}
df=pd.DataFrame(data)
print(df)

     Farm     Crop  Area_ha  Production_tons
0  Farm A    Wheat       10               30
1  Farm B     Rice       15               40
2  Farm C    Wheat       20               50
3  Farm D  Sorghum       36               60

In [ ]:
print(df.head())   #prints 1st few rows

     Farm     Crop  Area_ha  Production_tons
0  Farm A    Wheat       10               30
1  Farm B     Rice       15               40
2  Farm C    Wheat       20               50
3  Farm D  Sorghum       36               60

In [ ]:

df.head(2)  #prints 1st 2 rows

     Farm   Crop  Area_ha  Production_tons
0  Farm A  Wheat       10               30
1  Farm B   Rice       15               40

In [ ]:
df.tail()

     Farm     Crop  Area_ha  Production_tons
0  Farm A    Wheat       10               30
1  Farm B     Rice       15               40
2  Farm C    Wheat       20               50
3  Farm D  Sorghum       36               60

In [ ]:
df.tail(2)

     Farm     Crop  Area_ha  Production_tons
2  Farm C    Wheat       20               50
3  Farm D  Sorghum       36               60

In [ ]:
df.info()  #gives basic information

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Farm             4 non-null      object
 1   Crop             4 non-null      object
 2   Area_ha          4 non-null      int64
 3   Production_tons  4 non-null      int64
dtypes: int64(2), object(2)
memory usage: 260.0+ bytes

In [ ]:
df.describe() #gives basic summary in the form of statistics

        Area_ha  Production_tons
count   4.00000         4.000000
mean   20.25000        45.000000
std    11.26573        12.909944
min    10.00000        30.000000
25%    13.75000        37.500000
50%    17.50000        45.000000
75%    24.00000        52.500000
max    36.00000        60.000000

In [ ]:
#Add a new column
df["Yield_tons_per_ha"]=df["Production_tons"]/df["Area_ha"]  #permanently changes the data farme
print(df)

     Farm     Crop  Area_ha  Production_tons  Yield_tons_per_ha
0  Farm A    Wheat       10               30           3.000000
1  Farm B     Rice       15               40           2.666667
2  Farm C    Wheat       20               50           2.500000
3  Farm D  Sorghum       36               60           1.666667

In [ ]:
print(df.iloc[[1,3]])

     Farm     Crop  Area_ha  Production_tons  Yield_tons_per_ha
1  Farm B     Rice       15               40           2.666667
3  Farm D  Sorghum       36               60           1.666667

In [ ]:
df.iloc[[0,2,3]]

     Farm     Crop  Area_ha  Production_tons  Yield_tons_per_ha
0  Farm A    Wheat       10               30           3.000000
2  Farm C    Wheat       20               50           2.500000
3  Farm D  Sorghum       36               60           1.666667

In [ ]:
df.iloc[[0]]

     Farm   Crop  Area_ha  Production_tons  Yield_tons_per_ha
0  Farm A  Wheat       10               30                3.0

In [ ]:
df.iloc[[1,2,3],[0,2]]

     Farm  Area_ha
1  Farm B       15
2  Farm C       20
3  Farm D       36

In [ ]:
df.iloc[[1,3],[0,1,2]]

     Farm     Crop  Area_ha
1  Farm B     Rice       15
3  Farm D  Sorghum       36

In [ ]:
df.loc[[1,3],["Farm","Crop","Area_ha"]]

     Farm     Crop  Area_ha
1  Farm B     Rice       15
3  Farm D  Sorghum       36

In [ ]:
#slicing of columns
df.iloc[:][0:2]

     Farm   Crop  Area_ha  Production_tons  Yield_tons_per_ha
0  Farm A  Wheat       10               30           3.000000
1  Farm B   Rice       15               40           2.666667

In [ ]:
#filter data
#farms growing wheat
print(df['Crop']== 'Wheat')
print()
wheat_farms=df[df['Crop']=='Wheat']
print(wheat_farms)

0     True
1    False
2     True
3    False
Name: Crop, dtype: bool

     Farm   Crop  Area_ha  Production_tons  Yield_tons_per_ha
0  Farm A  Wheat       10               30                3.0
2  Farm C  Wheat       20               50                2.5

In [ ]:
#Farms with yield >3
high_yield=df[df["Yield_tons_per_ha"]>=3]
print(high_yield)

     Farm   Crop  Area_ha  Production_tons  Yield_tons_per_ha
0  Farm A  Wheat       10               30                3.0

In [ ]:
#Sort farms by by highest
sorted_df=df.sort_values(by="Production_tons",ascending=True)
print(sorted_df)

     Farm     Crop  Area_ha  Production_tons  Yield_tons_per_ha
0  Farm A    Wheat       10               30           3.000000
1  Farm B     Rice       15               40           2.666667
2  Farm C    Wheat       20               50           2.500000
3  Farm D  Sorghum       36               60           1.666667

In [ ]:
#GroupBy operation- Avg yield per crop
avg_yield= df.groupby("Crop")["Yield_tons_per_ha"].mean()  #gives mean value of yield of wheat
print(avg_yield)

Crop
Rice       2.666667
Sorghum    1.666667
Wheat      2.750000
Name: Yield_tons_per_ha, dtype: float64

In [ ]:
avg_yield= df.groupby("Crop")["Yield_tons_per_ha"].sum() #gives sum of yields of wheat
print(avg_yield)

Crop
Rice       2.666667
Sorghum    1.666667
Wheat      5.500000
Name: Yield_tons_per_ha, dtype: float64